In [1]:
TGT_CWD = '~/repos/binance-public-data/python'
import pathlib; import sys; sys.path.append(pathlib.Path(TGT_CWD).expanduser().as_posix())

from rsch.notebook_setup import *

setting up ipython for notebook
%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib

done configuring ipython

working directory : /home/tyler/repos/binance-public-data/python/rsch/notebooks

Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [4]:
import rsch.etl
rsch.etl.get_all_filenames_in_data_directory(trading_type='um', market_data_type='trades')
rsch.etl.get_all_filenames_in_data_directory(trading_type='um', market_data_type='klines', symbol='BTCUSDT')

/home/tyler/repos/binance-public-data/python/data/futures/um/monthly/trades/BTCUSDT

['BTCUSDT-trades-2020-02.zip',
 'BTCUSDT-trades-2020-03.zip',
 'BTCUSDT-trades-2020-01.zip']

/home/tyler/repos/binance-public-data/python/data/futures/um/monthly/klines/BTCUSDT/1m

['BTCUSDT-1m-2021-09.zip',
 'BTCUSDT-1m-2022-04.zip',
 'BTCUSDT-1m-2022-05.zip',
 'BTCUSDT-1m-2022-11.zip',
 'BTCUSDT-1m-2023-06.zip',
 'BTCUSDT-1m-2023-10.zip',
 'BTCUSDT-1m-2020-11.zip',
 'BTCUSDT-1m-2021-01.zip',
 'BTCUSDT-1m-2022-12.zip',
 'BTCUSDT-1m-2020-09.zip',
 'BTCUSDT-1m-2022-01.zip',
 'BTCUSDT-1m-2023-02.zip',
 'BTCUSDT-1m-2023-09.zip',
 'BTCUSDT-1m-2023-03.zip',
 'BTCUSDT-1m-2021-05.zip',
 'BTCUSDT-1m-2022-02.zip',
 'BTCUSDT-1m-2020-01.zip',
 'BTCUSDT-1m-2020-12.zip',
 'BTCUSDT-1m-2023-04.zip',
 'BTCUSDT-1m-2020-05.zip',
 'BTCUSDT-1m-2021-12.zip',
 'BTCUSDT-1m-2021-11.zip',
 'BTCUSDT-1m-2020-06.zip',
 'BTCUSDT-1m-2023-11.zip',
 'BTCUSDT-1m-2021-10.zip',
 'BTCUSDT-1m-2020-10.zip',
 'BTCUSDT-1m-2023-01.zip',
 'BTCUSDT-1m-2023-07.zip',
 'BTCUSDT-1m-2022-03.zip',
 'BTCUSDT-1m-2021-04.zip',
 'BTCUSDT-1m-2022-06.zip',
 'BTCUSDT-1m-2023-05.zip',
 'BTCUSDT-1m-2021-07.zip',
 'BTCUSDT-1m-2023-08.zip',
 'BTCUSDT-1m-2020-03.zip',
 'BTCUSDT-1m-2020-02.zip',
 'BTCUSDT-1m-2021-06.zip',
 'BTCUSDT-1m-2021-03.zip',
 'BTCUSDT-1m-2022-07.zip',
 'BTCUSDT-1m-2020-07.zip',
 'BTCUSDT-1m-2022-08.zip',
 'BTCUSDT-1m-2020-08.zip',
 'BTCUSDT-1m-2020-04.zip',
 'BTCUSDT-1m-2021-02.zip',
 'BTCUSDT-1m-2021-08.zip',
 'BTCUSDT-1m-2022-09.zip',
 'BTCUSDT-1m-2022-10.zip']

In [29]:
df = rsch.etl.get_secid_data(trading_type='um', market_data_type='klines', symbol='BTCUSDT')

In [15]:
df.head()
df.info()

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,month,filename,secid
0,2020-01-01 00:00:00,7189.4300,7190.5200,7177.0000,7182.4400,246.0920,2020-01-01 00:00:59.999,1767430.1612,336,46.6300,334813.1982,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT
1,2020-01-01 00:01:00,7182.4300,7182.4400,7178.7500,7179.0100,70.9090,2020-01-01 00:01:59.999,509145.7848,140,32.5970,234063.2788,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT
2,2020-01-01 00:02:00,7179.0100,7179.0100,7175.2500,7177.9300,99.4200,2020-01-01 00:02:59.999,713539.5535,148,16.3110,117066.9212,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT
3,2020-01-01 00:03:00,7177.7700,7182.6000,7177.0000,7181.1100,69.3300,2020-01-01 00:03:59.999,497793.3593,104,43.7230,313920.0298,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT
4,2020-01-01 00:04:00,7179.1000,7179.1000,7172.9400,7175.2500,97.3680,2020-01-01 00:04:59.999,698627.3938,193,36.6160,262734.6900,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT

<class 'pandas.core.frame.DataFrame'>
Index: 2059200 entries, 0 to 43199
Data columns (total 14 columns):
 #   Column                        Dtype
---  ------                        -----
 0   open_time                     datetime64[ns]
 1   open                          float64
 2   high                          float64
 3   low                           float64
 4   close                         float64
 5   volume                        float64
 6   close_time                    datetime64[ns]
 7   quote_asset_volume            float64
 8   number_of_trades              int64
 9   taker_buy_base_asset_volume   float64
 10  taker_buy_quote_asset_volume  float64
 11  month                         int64
 12  filename                      string
 13  secid                         string
dtypes: datetime64[ns](2), float64(8), int64(2), string(2)
memory usage: 235.7 MB

In [19]:
trading_type = 'um'
market_data_type = 'klines'

time_period='monthly'

all_syms = rsch.etl.get_all_symbols_in_data_direcory(
    trading_type='um',
    market_data_type='klines',
    time_period='monthly'
)

# for sym in tqdm(all_syms):
for sym in tqdm(all_syms):
    rsch.etl.load_secid_data_to_deltalake(
        trading_type='um',
        market_data_type='klines',
        time_period='monthly',
        symbol=sym,
        interval='1m'
    )
    break

  0%|          | 0/247 [00:00<?, ?it/s]

In [4]:
# conda install jupysql -c conda-forge

In [14]:
%load_ext sql
%sql duckdb://

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

MissingPackageError: Can't load plugin: sqlalchemy.dialects:duckdb

To fix it, run this in your notebook: %pip install duckdb-engine --quiet

For more details, see: https://jupysql.ploomber.io/en/latest/howto/db-drivers.html#duckdb
If you need help solving this issue, send us a message: https://ploomber.io/community

In [20]:
from deltalake import DeltaTable, write_deltalake
from tinydb import TinyDB, Query


dt = DeltaTable(rsch.etl.get_deltalake_table_path(
    trading_type='um',
    market_data_type='klines',
    interval='1m'
))
um_klines_1m = dt.to_pyarrow_dataset()

In [ ]:
from pathlib import Path
from deltalake import DeltaTable, write_deltalake
from tinydb import TinyDB, Query
import datetime
import deltalake
import duckdb


class DeltaLakeHouse:
    __version__ = '0.0.1'

    def __init__(self, path):
        self.path = Path(path)
        self.path.mkdir(parents=True, exist_ok=True)
        self.name = self.path.name
        self.metadata_path = self.path / '_metadata.json'
        self.metadata_db = TinyDB(self.metadata_path.as_posix())

        if not self.metadata_db.all():
            self.metadata_db.insert({
                'metadata': {
                    'deltalakehouse_name': self.name,
                    'deltalakehouse_path': self.path.as_posix(),
                    'created': datetime.datetime.now().isoformat(),
                    'metadata_path': self.metadata_path.as_posix(),
                    'deltalakehouse_version': self.__version__,
                    'deltalake_version': deltalake.__version__
                }
            }
            self.metadata_db.insert({'tables': []})
        
        self.conn = duckdb.connect(database=':memory:', read_only=False)
    
    def _get_table_path(self, table_name):
        return self.path / table_name
    
    def _list_tables(self):
        table_paths = self.path.glob('*')
        return [table_path.name for table_path in table_paths]
    
    def _update_registered_tables(self):
        """
        update tables and schemas registered in duckdb connection. we read through
        all table names in self.path and register them in duckdb connection. this way
        they can be queried directly using sql.
        """
        for table_name in self._list_tables():
            table_path = self._get_table_path(table_name)
            deltatable = DeltaTable(table_path.as_posix())
            deltatable_arrow_dataset = deltatable.to_pyarrow_dataset()

            # Extract the schema name
            schema_name = '.'.join(table_name.split('.')[:-1])
            self.conn.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

            # Extract the DataFrame name
            table_name = name.split('.')[-1]
            full_name = f"{schema}.{table_name}"
            
            # Register DataFrame in the schema
            conn.register(full_name, df)
    
    def write(table_name, df, mode='append', **kwargs):
        if not self.metadata_db.search(Query().name == table_name):
            self.metadata_db.insert({
                'name': table_name,
                'path': self.get_table_path(table_name).as_posix()
                'created': datetime.datetime.now().isoformat(),
            })

        table_path = self.get_table_path(table_name)

        write_deltalake(table_path, df, mode=mode, **kwargs)

        self._update_registered_tables()
    
    def query(self, query):
        self._update_registered_tables()

        return self.conn.execute(query).fetchdf()

In [62]:
from pathlib import Path
from deltalake import DeltaTable, write_deltalake
from tinydb import TinyDB, Query
import datetime
import deltalake
import duckdb

class DeltaLakeHouse:
    __version__ = '0.0.1'

    def __init__(self, path):
        self.path = Path(path)
        self.path.mkdir(parents=True, exist_ok=True)
        self.name = self.path.name
        self.metadata_path = self.path / '_lakehouse_metadata.json'
        self.metadata_db = TinyDB(self.metadata_path.as_posix())

        if not self.metadata_db.all():
            self.metadata_db.insert({'metadata': {
                'deltalakehouse_name': self.name,
                'deltalakehouse_path': self.path.as_posix(),
                'created': datetime.datetime.now().isoformat(),
                'metadata_path': self.metadata_path.as_posix(),
                'deltalakehouse_version': self.__version__,
                'deltalake_version': deltalake.__version__,
            }})
            self.metadata_db.insert({'tables': []})
        
        self.conn = duckdb.connect(database=':memory:', read_only=False)
        self.tables = {}
        self._update_tables()
        self._update_registered_tables()
    
    def _update_tables(self):
        table_paths = [p for p in self.path.iterdir() if p.is_dir() and (p / '_delta_log').is_dir()]
        self.tables = {
            table_path.name: {
                'table_name': table_path.name,
                'table_path': table_path,
                'deltatable': DeltaTable(table_path),
                'deltatable_arrow_dataset': DeltaTable(table_path).to_pyarrow_dataset(),
            }
            for table_path in table_paths
        }
    
    def _get_table_path(self, table_name):
        return self.path / table_name
    
    def _list_tables(self):
        table_paths = [p for p in self.path.iterdir() if p.is_dir() and (p / '_delta_log').is_dir()]
        return [table_path.name for table_path in table_paths]
    
    def _update_registered_tables(self):
        for table_name in self._list_tables():
            table_path = self._get_table_path(table_name)
            deltatable = DeltaTable(table_path.as_posix())
            deltatable_arrow_dataset = deltatable.to_pyarrow_dataset()
            self.conn.register(table_name, deltatable_arrow_dataset)
    
    def write(self, table_name, df, mode='append', **kwargs):
        if not self.metadata_db.search(Query().name == table_name):
            self.metadata_db.insert({
                'name': table_name,
                'path': self._get_table_path(table_name).as_posix(),
                'created': datetime.datetime.now().isoformat(),
            })

        table_path = self._get_table_path(table_name)
        write_deltalake(table_path, df, mode=mode, **kwargs)
        
        self._update_registered_tables()
    
    def query(self, query):
        self._update_registered_tables()
        return self.conn.execute(query).fetchdf()

In [72]:
from pathlib import Path
from deltalake import DeltaTable, write_deltalake
from tinydb import TinyDB, Query
import datetime
import deltalake
import duckdb

class DeltaLakeHouse:
    __version__ = '0.0.1'

    def __init__(self, path):
        self.path = Path(path)
        self.path.mkdir(parents=True, exist_ok=True)
        self.name = self.path.name
        self.metadata_path = self.path / '_metadata.json'
        self.metadata_db = TinyDB(str(self.metadata_path))

        if not self.metadata_db.all():
            self.metadata_db.insert({'metadata': {
                'deltalakehouse_name': self.name,
                'deltalakehouse_path': self.path.as_posix(),
                'created': datetime.datetime.now().isoformat(),
                'metadata_path': str(self.metadata_path),
                'deltalakehouse_version': self.__version__,
                'deltalake_version': deltalake.__version__,
            }})
            self.metadata_db.insert({'tables': []})
        
        self.conn = duckdb.connect(database=':memory:', read_only=False)
        self._update_registered_tables()
    
    def get_tables(self):
        table_paths = [p for p in self.path.iterdir() if p.is_dir() and (p / '_delta_log').is_dir()]
        return {
            table_path.name: {
                'table_name': table_path.name,
                'table_path': table_path,
                'table_schema': '.'.join(table_path.name.split('.')[:-1]),
                'deltatable': DeltaTable(table_path),
                'deltatable_arrow_dataset': DeltaTable(table_path).to_pyarrow_dataset(),
            }
            for table_path in table_paths
        }
    
    def _update_registered_tables(self):
        for table_name, table_data in self.get_tables().items():
            # self.conn.execute(f"CREATE SCHEMA IF NOT EXISTS {table_data['table_schema']}")
            self.conn.register(table_name, table_data['deltatable_arrow_dataset'])
    
    def write(self, table_name, df, mode='append', **kwargs):
        if not self.metadata_db.search(Query().name == table_name):
            self.metadata_db.insert({
                'name': table_name,
                'path': str(self._get_table_path(table_name)),
                'created': datetime.datetime.now().isoformat(),
            })

        table_path = self.get_tables()[table_name]['table_path']
        write_deltalake(table_path, df, mode=mode, **kwargs)
        self._update_registered_tables()
    
    def query(self, query):
        self._update_registered_tables()
        # return self.conn.execute(query).fetchdf()
        return self.conn.sql(query).df()


# def _update_tables(self):
#     table_paths = [p for p in self.path.iterdir() if p.is_dir() and (p / '_delta_log').is_dir()]
#     self.tables = {
#         table_path.name: {
#             'table_name': table_path.name,
#             'table_path': table_path,
#             'deltatable': DeltaTable(table_path),
#             'deltatable_arrow_dataset': DeltaTable(table_path).to_pyarrow_dataset(),
#         }
#         for table_path in table_paths
#     }

In [18]:
from pathlib import Path
from deltalake import DeltaTable, write_deltalake
from tinydb import TinyDB, Query
import datetime
import deltalake
import duckdb
import pandas as pd
import numpy as np
import pyarrow as pa
from typing import Dict, Any, List, Optional, Union, Iterable, Tuple, Callable


class DeltaLakeHouse:
    __version__ = '0.0.1'

    def __init__(self, path):
        """
        Initialize the DeltaLakeHouse instance.

        Args:
            path: The file system path for storing Delta Lake tables.
        """
        self.path = Path(path)
        self.path.mkdir(parents=True, exist_ok=True)
        self.name = self.path.name
        self.metadata_path = self.path / '_metadata.json'
        self.metadata_db = TinyDB(str(self.metadata_path))

        if not self.metadata_db.all():
            self.metadata_db.insert({'metadata': {
                'deltalakehouse_name': self.name,
                'deltalakehouse_path': str(self.path),
                'created': datetime.datetime.now().isoformat(),
                'metadata_path': str(self.metadata_path),
                'deltalakehouse_version': self.__version__,
                'deltalake_version': deltalake.__version__,
            }})
            self.metadata_db.insert({'tables': []})

        self.conn = duckdb.connect(database=':memory:', read_only=False)
        self._update_sql_registry()
    
    def __getitem__(self, table_name: str) -> DeltaTable:
        """
        Get the DeltaTable object for a given table name using dictionary-like access.

        Args:
            table_name: The name of the table.

        Returns:
            The DeltaTable object corresponding to the table name.

        Raises:
            KeyError: If the table name does not exist.
        """
        if table_name not in self.tables:
            # possible that a new table is not registered in DuckDB yet
            self._update_sql_registry()
        
        return DeltaTable(str(self.tables[table_name]['table_path']))

    @property
    def tables(self) -> Dict[str, Dict[str, Any]]:
        """
        Get a dictionary of Delta Lake tables with their metadata.

        Returns:
            A dictionary where each key is a table name and the value is a dictionary of table metadata.
        """
        table_paths = [p for p in self.path.iterdir() if p.is_dir() and (p / '_delta_log').is_dir()]
        return {
            table_path.name: {
                'table_name': table_path.name,
                'table_path': table_path,
                'table_schema': '.'.join(table_path.name.split('.')[:-1]),
            }
            for table_path in table_paths
        }
    
    def _get_table_path(self, table_name: str) -> Path:
        """
        Get the file path for a given table name.

        Args:
            table_name: The name of the table.

        Returns:
            The file path of the table.
        """
        return self.path / table_name

    def _update_sql_registry(self):
        """
        Update the registered tables in DuckDB as arrow datasets so we can query them using SQL.
        """
        for table_name, table_data in self.tables.items():
            if table_name not in self.query('show tables').name.values:
                deltatable_arrow_dataset = DeltaTable(str(table_data['table_path'])).to_pyarrow_dataset()
                self.conn.register(table_name, deltatable_arrow_dataset)

    def write_deltalake(self, table_name: str, df: pd.DataFrame, mode: str = 'append', **kwargs):
        """
        Write a DataFrame to a specified Delta Lake table. mirrors the behavior of deltalake.write_deltalake,
        but only need to provide the table_name as an argument.

        Args:
            table_name: The name of the table.
            df: The DataFrame to write.
            mode: The write mode, default is 'append'.
        """
        table_path = self.tables[table_name].get('table_path', self._get_table_path(table_name))
        write_deltalake(str(table_path), df, mode=mode, **kwargs)
        self._update_sql_registry()

    def sql(self, query: str, return_method: str='df') -> Union[pd.DataFrame, pa.Table, np.ndarray, Any]:
        """
        Execute a SQL query using DuckDB. Convenience method for e.g. `self.conn.sql(query).df()`.

        Args:
            query: The SQL query to execute.
            return_method: The return method, called on the relation `self.conn.sql`. determines the
                type of object returned by the query. default is 'df' for DataFrame. options can be
                viewed here - https://duckdb.org/docs/api/python/overview.html#result-conversion.
                defaults to pandas dataframe.

        Returns:
            The result of the query as a DataFrame.
        """
        try:
            return getattr(self.conn.sql(query), return_method)()
        except duckdb.CatalogException as e:
            # possible that a new table is not registered in DuckDB yet
            print(f'Error: {e}')
            print(f'Updating SQL registry and retrying query...')
            self._update_sql_registry()

            return getattr(self.conn.sql(query), return_method)()
            # return self.conn.sql(query).df()

In [20]:
from rsch.lakeshack import LakeShack

ModuleNotFoundError: No module named 'rsch'

In [13]:
dlh_path = '/home/tyler/repos/binance-public-data/python/data/deltalakehouse'

dlh = DeltaLakeHouse(dlh_path)

In [14]:
dlh.query('show tables').name.values

array(['um.klines.1m'], dtype=object)

In [4]:
dlh.conn.sql('create schema if not exists a.b.c')

ParserException: Parser Error: CREATE SCHEMA too many dots: expected "catalog.schema" or "schema"
LINE 1: create schema if not exists a.b.c
                                    ^

In [17]:
dlh['um.klines.1m'].version()

0

In [5]:
dlh.tables
dlh.deltatables

{'um.klines.1m': DeltaTable()}

In [6]:
dlh.tables

{'um.klines.1m': {'table_name': 'um.klines.1m',
  'table_path': PosixPath('/home/tyler/repos/binance-public-data/python/data/deltalakehouse/um.klines.1m'),
  'table_schema': 'um.klines'}}

In [7]:
dlh.deltatables['um.klines.1m'].metadata().created_time

1703363868815

In [8]:
# dlh.write('um.klines.1m', df)

In [9]:
# dlh.get_tables()

In [11]:
dlh.query('select * from "um.klines.1m" limit 10').head()

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,month,filename,secid,__index_level_0__
0,2020-01-01 00:00:00,7189.43,7190.52,7177.00,7182.44,246.092,2020-01-01 00:00:59.999,1.767430e+06,336,46.630,334813.19820,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,0
1,2020-01-01 00:01:00,7182.43,7182.44,7178.75,7179.01,70.909,2020-01-01 00:01:59.999,5.091458e+05,140,32.597,234063.27884,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,1
2,2020-01-01 00:02:00,7179.01,7179.01,7175.25,7177.93,99.420,2020-01-01 00:02:59.999,7.135396e+05,148,16.311,117066.92118,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,2
3,2020-01-01 00:03:00,7177.77,7182.60,7177.00,7181.11,69.330,2020-01-01 00:03:59.999,4.977934e+05,104,43.723,313920.02981,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,3
4,2020-01-01 00:04:00,7179.10,7179.10,7172.94,7175.25,97.368,2020-01-01 00:04:59.999,6.986274e+05,193,36.616,262734.68999,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,4

In [92]:
duckdb.CatalogException

duckdb.duckdb.CatalogException

In [90]:
qry = """
SELECT * FROM 'um.klines.1m'
where secid = 'BTCUSDT'
"""

dlh.query(qry)

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,month,filename,secid,__index_level_0__
0,2020-01-01 00:00:00,7189.4300,7190.5200,7177.0000,7182.4400,246.0920,2020-01-01 00:00:59.999,1767430.1612,336,46.6300,334813.1982,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,0
1,2020-01-01 00:01:00,7182.4300,7182.4400,7178.7500,7179.0100,70.9090,2020-01-01 00:01:59.999,509145.7848,140,32.5970,234063.2788,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,1
2,2020-01-01 00:02:00,7179.0100,7179.0100,7175.2500,7177.9300,99.4200,2020-01-01 00:02:59.999,713539.5535,148,16.3110,117066.9212,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,2
3,2020-01-01 00:03:00,7177.7700,7182.6000,7177.0000,7181.1100,69.3300,2020-01-01 00:03:59.999,497793.3593,104,43.7230,313920.0298,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,3
4,2020-01-01 00:04:00,7179.1000,7179.1000,7172.9400,7175.2500,97.3680,2020-01-01 00:04:59.999,698627.3938,193,36.6160,262734.6900,202001,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2059195,2023-11-30 23:55:00,37699.9000,37701.9000,37698.6000,37698.6000,29.0830,2023-11-30 23:55:59.999,1096434.5391,379,21.7700,820730.5290,202311,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,43195
2059196,2023-11-30 23:56:00,37698.6000,37698.7000,37696.0000,37696.1000,6.0720,2023-11-30 23:56:59.999,228891.8584,243,3.8750,146072.4135,202311,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,43196
2059197,2023-11-30 23:57:00,37696.0000,37696.1000,37691.8000,37691.9000,24.2870,2023-11-30 23:57:59.999,915464.9194,431,7.5100,283078.4624,202311,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,43197
2059198,2023-11-30 23:58:00,37691.9000,37697.8000,37691.8000,37697.8000,20.9630,2023-11-30 23:58:59.999,790187.1637,350,17.4260,656859.9341,202311,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,43198
2059199,2023-11-30 23:59:00,37697.7000,37716.9000,37691.9000,37716.8000,54.2180,2023-11-30 23:59:59.999,2044064.1023,963,44.7460,1686964.8556,202311,/home/tyler/repos/binance-public-data/python/d...,BTCUSDT,43199

In [32]:
dlh._get_table_path('um.klines.1m')

PosixPath('/home/tyler/repos/binance-public-data/python/data/deltalakehouse/um.klines.1m')

In [24]:
import duckdb
import pandas as pd

# Example DataFrame
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})

# Connect to DuckDB
conn = duckdb.connect(database=':memory:', read_only=False)

# Register DataFrame with a 'virtual namespace'
conn.register('namespace1.df', df)

# Query using the 'virtual namespace'
result = conn.execute("SELECT * FROM namespace1.df").fetchdf()

print(result)

CatalogException: Catalog Error: Table with name df does not exist!
Did you mean "temp.pg_catalog.pg_am"?
LINE 1: SELECT * FROM namespace1.df
                      ^

In [21]:
import duckdb


qry = """
select * from um_klines_1m
"""
duckdb.sql(qry).df()

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,month,filename,secid
0,2021-02-19 07:00:00,23.1000,26.3900,23.1000,25.6190,2515.4000,2021-02-19 07:00:59.999,64606.2968,1665,1643.4000,42300.1774,202102,/home/tyler/repos/binance-public-data/python/d...,UNFIUSDT
1,2021-02-19 07:01:00,25.6190,25.9320,25.6190,25.7010,1192.0000,2021-02-19 07:01:59.999,30659.0047,573,496.9000,12795.9303,202102,/home/tyler/repos/binance-public-data/python/d...,UNFIUSDT
2,2021-02-19 07:02:00,25.7010,25.7160,25.4010,25.4550,851.5000,2021-02-19 07:02:59.999,21704.0265,148,379.9000,9684.5288,202102,/home/tyler/repos/binance-public-data/python/d...,UNFIUSDT
3,2021-02-19 07:03:00,25.4770,25.6870,25.4010,25.4170,1089.6000,2021-02-19 07:03:59.999,27736.5687,96,293.1000,7475.5228,202102,/home/tyler/repos/binance-public-data/python/d...,UNFIUSDT
4,2021-02-19 07:04:00,25.4200,25.6280,25.4090,25.4420,81.7000,2021-02-19 07:04:59.999,2078.4310,26,80.2000,2040.3175,202102,/home/tyler/repos/binance-public-data/python/d...,UNFIUSDT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1458295,2023-11-30 23:55:00,11.5630,11.5630,11.5550,11.5610,1048.1000,2023-11-30 23:55:59.999,12114.2176,125,767.4000,8869.2461,202311,/home/tyler/repos/binance-public-data/python/d...,UNFIUSDT
1458296,2023-11-30 23:56:00,11.5620,11.5630,11.5590,11.5590,242.0000,2023-11-30 23:56:59.999,2797.9077,39,122.3000,1414.0190,202311,/home/tyler/repos/binance-public-data/python/d...,UNFIUSDT
1458297,2023-11-30 23:57:00,11.5580,11.5620,11.5550,11.5590,873.5000,2023-11-30 23:57:59.999,10095.6320,86,522.8000,6042.1980,202311,/home/tyler/repos/binance-public-data/python/d...,UNFIUSDT
1458298,2023-11-30 23:58:00,11.5610,11.5610,11.5530,11.5570,794.4000,2023-11-30 23:58:59.999,9182.1823,94,69.1000,798.5302,202311,/home/tyler/repos/binance-public-data/python/d...,UNFIUSDT
1458299,2023-11-30 23:59:00,11.5570,11.5610,11.5500,11.5610,592.0000,2023-11-30 23:59:59.999,6840.7766,223,231.9000,2679.9062,202311,/home/tyler/repos/binance-public-data/python/d...,UNFIUSDT

In [19]:
%%sql

select * from um_klines_1m

UsageError: No active connection.

To fix it:

Pass a valid connection string:
    Example: %sql postgresql://username:password@hostname/dbname

OR

Set the environment variable $DATABASE_URL

For more details, see: https://jupysql.ploomber.io/en/latest/connecting.html
If you need help solving this issue, send us a message: https://ploomber.io/community

In [7]:
# trades_syms = ['BTCUSDT', 'ETHUSDT']

# for sym in tqdm(trades_syms):
#     fnames = rsch.etl.get_all_filenames_in_data_directory(
#         trading_type='um',
#         market_data_type='trades'
#         symbol=sym
#     )

#     for fname in tqdm(fnames):
#         rsch.etl.load_secid_data_to_deltalake(
#             trading_type='um',
#             market_data_type='trades',
#             time_period='monthly',
#             symbol=sym,
#             interval='1m'
#         )

In [3]:
# all_syms[all_syms.index('JTOUSDT'):]

In [9]:
len(rsch.etl.get_all_symbols_in_data_direcory(market_data_type='trades'))

2

In [4]:
# df = rsch.etl.get_secid_data_pa()
df = rsch.etl.get_secid_data(symbol='ETHUSDT')

open_time
open
high
low
close
volume
close_time
quote_asset_volume
number_of_trades
taker_buy_base_asset_volume
taker_buy_quote_asset_volume
ignore

In [15]:
df

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume
0,2020-01-01 00:00:00,129.1200,129.1200,128.9100,128.9700,289.0400,2020-01-01 00:00:59.999,37296.6722,18.0000,155.1070,20005.4435
1,2020-01-01 00:01:00,128.9500,129.0400,128.9300,128.9400,695.5660,2020-01-01 00:01:59.999,89717.0649,49.0000,284.5360,36703.7750
2,2020-01-01 00:02:00,128.9300,128.9700,128.9200,128.9200,131.9020,2020-01-01 00:02:59.999,17008.7067,17.0000,107.8650,13908.7548
3,2020-01-01 00:03:00,128.9700,128.9800,128.9300,128.9600,455.5720,2020-01-01 00:03:59.999,58748.9755,19.0000,306.0330,39464.2887
4,2020-01-01 00:04:00,128.9500,128.9500,128.7600,128.8100,866.1170,2020-01-01 00:04:59.999,111594.8402,48.0000,273.5950,35249.0893
...,...,...,...,...,...,...,...,...,...,...,...
43195,2023-11-30 23:55:00,2051.8500,2052.5400,2051.8400,2052.2600,731.4380,2023-11-30 23:55:59.999,1501002.6258,780.0000,480.1360,985307.4556
43196,2023-11-30 23:56:00,2052.2600,2052.2700,2051.8300,2051.8300,343.7720,2023-11-30 23:56:59.999,705403.0832,431.0000,80.7340,165656.9531
43197,2023-11-30 23:57:00,2051.8300,2051.9500,2051.6000,2051.9500,416.8680,2023-11-30 23:57:59.999,855290.0400,442.0000,133.0170,272908.8964
43198,2023-11-30 23:58:00,2051.9500,2051.9500,2051.6600,2051.6600,315.5490,2023-11-30 23:58:59.999,647440.9439,495.0000,119.4370,245055.1722
43199,2023-11-30 23:59:00,2051.6600,2051.7700,2050.1300,2051.7600,2680.3270,2023-11-30 23:59:59.999,5497613.0553,1702.0000,709.6900,1455456.6169

In [5]:
rsch.etl.load_secid_data_to_deltalake()

/home/tyler/repos/binance-public-data/python/data/deltalake/um.klines.1m
open_time
open
high
low
close
volume
close_time
quote_asset_volume
number_of_trades
taker_buy_base_asset_volume
taker_buy_quote_asset_volume
ignore
writing to: /home/tyler/repos/binance-public-data/python/data/deltalake/um.klines.1m

In [5]:
df.set_index('open_time').loc['2023-11-30']

,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume
open_time,,,,,,,,,,
2023-11-30 00:01:41.376,2027.8400,2028.4200,2027.4100,2027.4200,586.6090,2023-11-30 00:01:41.376,1189648.6416,646.0000,151.7130,307695.5876
2023-11-30 00:01:41.376,2027.4200,2027.6300,2026.5700,2026.5700,589.4090,2023-11-30 00:03:52.448,1194789.6034,705.0000,156.5840,317444.3257
2023-11-30 00:03:52.448,2026.5700,2026.9900,2026.4500,2026.6600,429.1300,2023-11-30 00:03:52.448,869707.9617,553.0000,177.8510,360427.2663
2023-11-30 00:03:52.448,2026.6700,2026.8800,2026.3600,2026.8700,447.7770,2023-11-30 00:06:03.520,907435.2607,479.0000,175.9150,356499.9682
2023-11-30 00:06:03.520,2026.8800,2026.9300,2026.5700,2026.6200,421.5820,2023-11-30 00:06:03.520,854448.6812,595.0000,188.4960,382023.2809
...,...,...,...,...,...,...,...,...,...,...
2023-11-30 23:54:44.608,2051.8500,2052.5400,2051.8400,2052.2600,731.4380,2023-11-30 23:56:55.680,1501002.6258,780.0000,480.1360,985307.4556
2023-11-30 23:56:55.680,2052.2600,2052.2700,2051.8300,2051.8300,343.7720,2023-11-30 23:56:55.680,705403.0832,431.0000,80.7340,165656.9531
2023-11-30 23:56:55.680,2051.8300,2051.9500,2051.6000,2051.9500,416.8680,2023-11-30 23:56:55.680,855290.0400,442.0000,133.0170,272908.8964
2023-11-30 23:56:55.680,2051.9500,2051.9500,2051.6600,2051.6600,315.5490,2023-11-30 23:59:06.752,647440.9439,495.0000,119.4370,245055.1722
2023-11-30 23:59:06.752,2051.6600,2051.7700,2050.1300,2051.7600,2680.3270,2023-11-30 23:59:06.752,5497613.0553,1702.0000,709.6900,1455456.6169

In [29]:
pd.isnull(pd.to_numeric(df.iloc[0, 0], errors='coerce'))

True

In [26]:
df

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume
0,2020-01-01 00:00:00.000,129.1200,129.1200,128.9100,128.9700,289.0400,2020-01-01 00:00:59.999,37296.6722,18.0000,155.1070,20005.4435
1,2020-01-01 00:01:00.000,128.9500,129.0400,128.9300,128.9400,695.5660,2020-01-01 00:01:59.999,89717.0649,49.0000,284.5360,36703.7750
2,2020-01-01 00:02:00.000,128.9300,128.9700,128.9200,128.9200,131.9020,2020-01-01 00:02:59.999,17008.7067,17.0000,107.8650,13908.7548
3,2020-01-01 00:03:00.000,128.9700,128.9800,128.9300,128.9600,455.5720,2020-01-01 00:03:59.999,58748.9755,19.0000,306.0330,39464.2887
4,2020-01-01 00:04:00.000,128.9500,128.9500,128.7600,128.8100,866.1170,2020-01-01 00:04:59.999,111594.8402,48.0000,273.5950,35249.0893
...,...,...,...,...,...,...,...,...,...,...,...
43196,2023-11-30 23:54:44.608,2051.8500,2052.5400,2051.8400,2052.2600,731.4380,2023-11-30 23:56:55.680,1501002.6258,780.0000,480.1360,985307.4556
43197,2023-11-30 23:56:55.680,2052.2600,2052.2700,2051.8300,2051.8300,343.7720,2023-11-30 23:56:55.680,705403.0832,431.0000,80.7340,165656.9531
43198,2023-11-30 23:56:55.680,2051.8300,2051.9500,2051.6000,2051.9500,416.8680,2023-11-30 23:56:55.680,855290.0400,442.0000,133.0170,272908.8964
43199,2023-11-30 23:56:55.680,2051.9500,2051.9500,2051.6600,2051.6600,315.5490,2023-11-30 23:59:06.752,647440.9439,495.0000,119.4370,245055.1722
43200,2023-11-30 23:59:06.752,2051.6600,2051.7700,2050.1300,2051.7600,2680.3270,2023-11-30 23:59:06.752,5497613.0553,1702.0000,709.6900,1455456.6169

In [11]:
df.sort_values('open_time', inplace=True)

In [19]:
df.set_index('open_time').loc[:'2023-06-28']

,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume
open_time,,,,,,,,,,
2020-01-01 00:00:00.000,129.1200,129.1200,128.9100,128.9700,289.0400,2020-01-01 00:00:59.999,37296.6722,18.0000,155.1070,20005.4435
2020-01-01 00:01:00.000,128.9500,129.0400,128.9300,128.9400,695.5660,2020-01-01 00:01:59.999,89717.0649,49.0000,284.5360,36703.7750
2020-01-01 00:02:00.000,128.9300,128.9700,128.9200,128.9200,131.9020,2020-01-01 00:02:59.999,17008.7067,17.0000,107.8650,13908.7548
2020-01-01 00:03:00.000,128.9700,128.9800,128.9300,128.9600,455.5720,2020-01-01 00:03:59.999,58748.9755,19.0000,306.0330,39464.2887
2020-01-01 00:04:00.000,128.9500,128.9500,128.7600,128.8100,866.1170,2020-01-01 00:04:59.999,111594.8402,48.0000,273.5950,35249.0893
...,...,...,...,...,...,...,...,...,...,...
2023-06-28 23:54:25.152,1827.0300,1827.8600,1827.0300,1827.8500,626.8840,2023-06-28 23:54:25.152,1145570.4059,893.0000,267.5500,488900.8514
2023-06-28 23:56:36.224,1827.9900,1828.0000,1827.5000,1827.6600,263.3680,2023-06-28 23:58:47.296,481376.7362,480.0000,137.1930,250744.1564
2023-06-28 23:56:36.224,1827.9000,1828.0000,1827.6600,1828.0000,278.2050,2023-06-28 23:56:36.224,508507.9398,512.0000,205.1010,374882.2491
2023-06-28 23:58:47.296,1827.1500,1827.3100,1827.1400,1827.2600,217.3830,2023-06-29 00:00:58.368,397197.6116,541.0000,110.2620,201468.5518
2023-06-28 23:58:47.296,1827.6600,1827.6600,1826.7500,1827.1500,907.5060,2023-06-28 23:58:47.296,1658048.0021,1092.0000,312.7040,571303.5172

In [7]:
rsch.etl.load_secid_data_to_deltalake()

/home/tyler/repos/binance-public-data/python/data/deltalake/um.klines.1m

In [3]:
trading_type='um'
market_data_type='klines'
time_period='monthly'
symbol='BTCUSDT'
interval='1m'
time_period_filename=None

In [9]:
qw = pd.read_csv('/home/tyler/repos/binance-public-data/python/data/futures/um/monthly/klines/BTCUSDT/1m/BTCUSDT-1m-2023-11.zip', header=0)

In [7]:
pd.to_datetime(qw.open_time, unit='ms', origin='unix')

AttributeError: 'DataFrame' object has no attribute 'open_time'

In [11]:
qw

,open_time,open,high,low,close,volume,close_time,quote_volume,count,taker_buy_volume,taker_buy_quote_volume,ignore
0,1698796800000,34651.4000,34676.5000,34650.0000,34669.9000,376.0400,1698796859999,13036100.9289,4214,199.8850,6929500.6567,0
1,1698796860000,34669.9000,34684.0000,34637.3000,34637.4000,431.1770,1698796919999,14948280.1209,4495,229.4900,7957307.9510,0
2,1698796920000,34637.4000,34653.4000,34632.5000,34651.4000,175.8940,1698796979999,6093655.2986,2669,71.4940,2476893.3209,0
3,1698796980000,34651.3000,34651.4000,34608.6000,34621.1000,476.5870,1698797039999,16500972.8496,5182,89.6130,3102759.3142,0
4,1698797040000,34621.1000,34622.6000,34592.0000,34615.4000,546.3120,1698797099999,18903900.1304,5557,214.9620,7438202.9314,0
...,...,...,...,...,...,...,...,...,...,...,...,...
43195,1701388500000,37699.9000,37701.9000,37698.6000,37698.6000,29.0830,1701388559999,1096434.5391,379,21.7700,820730.5290,0
43196,1701388560000,37698.6000,37698.7000,37696.0000,37696.1000,6.0720,1701388619999,228891.8584,243,3.8750,146072.4135,0
43197,1701388620000,37696.0000,37696.1000,37691.8000,37691.9000,24.2870,1701388679999,915464.9194,431,7.5100,283078.4624,0
43198,1701388680000,37691.9000,37697.8000,37691.8000,37697.8000,20.9630,1701388739999,790187.1637,350,17.4260,656859.9341,0
43199,1701388740000,37697.7000,37716.9000,37691.9000,37716.8000,54.2180,1701388799999,2044064.1023,963,44.7460,1686964.8556,0

In [12]:
pd.isnull(pd.to_numeric(qw.columns[0], errors='coerce'))

True